Repository learnhubmk/api, pull requests merged in 2024-03, with the labels that each got.

#25 Feature/implement socialite
  .env.example
  README.md
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  config/services.php
Labels: enhancement, backend

#28 set up sanctum
  app/Http/Kernel.php
  app/Providers/AppServiceProvider.php
Labels: enhancement

#31 Laravel modular
  app/Admin/composer.json
  app/Admin/database/factories/.gitkeep
  app/Admin/database/migrations/.gitkeep
  app/Admin/database/seeders/.gitkeep
  app/Admin/routes/admin-routes.php
  app/Admin/src/Providers/AdminServiceProvider.php
  app/Platform/composer.json
  app/Platform/database/factories/.gitkeep
  app/Platform/database/migrations/.gitkeep
  app/Platform/routes/platform-routes.php
  app/Platform/src/Providers/PlatformServiceProvider.php
  app/Website/composer.json
  app/Website/database/factories/.gitkeep
  app/Website/database/migrations/.gitkeep
  app/Website/database/seeders/.gitkeep
  app/Website/routes/website-routes.php
  app/Website/src/Providers/WebsiteServiceProvider.php
  composer.json
  composer.lock
  config/app-modules.php
  phpunit.xml
Labels: enhancement, API, backend

#41 Set up roles and permissions
  app/Admin/src/Providers/AdminServiceProvider.php
  app/Http/Kernel.php
  app/Models/User.php
  app/Platform/Enums/RoleName.php
  app/Platform/database/migrations/2024_03_13_221556_insert_roles_into_roles_table.php
  app/Platform/database/seeders/RoleSeeder.php
  app/Platform/src/Providers/PlatformServiceProvider.php
  app/Providers/AppServiceProvider.php
  app/Website/routes/website-routes.php
  app/Website/src/Providers/WebsiteServiceProvider.php
  composer.json
  composer.lock
  config/app-modules.php
  config/permission.php
  database/migrations/2024_03_13_190854_create_permission_tables.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement, API, backend

#51 48 be implement the blog post tags api endpoint
  .scribe/.filehashes
  .scribe/endpoints.cache/00.yaml
  .scribe/endpoints/00.yaml
  .scribe/intro.md
  app/Website/database/seeders/TagSeeder.php
  app/Website/routes/website-routes.php
  app/Website/src/Http/Controllers/BlogPostController.php
  app/Website/src/Http/Controllers/BlogTagsController.php
  config/scribe.php
  public/docs/collection.json
  public/docs/index.html
  public/docs/openapi.yaml
Labels: API, backend, website module

#53 44 be implement the blog posts by tag api endpoint
  .scribe/endpoints.cache/00.yaml
  .scribe/endpoints/00.yaml
  app/Website/routes/website-routes.php
  app/Website/src/Http/Controllers/BlogPostController.php
  app/Website/src/Http/Controllers/BlogTagsController.php
  public/docs/collection.json
  public/docs/index.html
  public/docs/openapi.yaml
Labels: API, backend, website module

#54 enhancement: upgrade to laravel 11
  composer.json
  composer.lock
Labels: enhancement, API, backend

#61 #57: chore: Laravel Telescope Installed
  app/Providers/AppServiceProvider.php
  app/Providers/TelescopeServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/telescope.php
  database/migrations/2018_08_08_100000_create_telescope_entries_table.php
  public/vendor/telescope/app-dark.css
  public/vendor/telescope/app.css
  public/vendor/telescope/app.js
  public/vendor/telescope/favicon.ico
  public/vendor/telescope/mix-manifest.json
Labels: API, backend
